# Generated by Django 2.0.3 on 2018-03-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('genre_name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
