# Generated by Django 2.0.3 on 2018-03-12 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='created',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='modified',
        ),
    ]
