# Generated by Django 2.0.3 on 2018-03-12 02:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0002_auto_20180312_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 12, 2, 34, 14, 227760, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
