# Generated by Django 2.0.3 on 2018-03-12 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0004_artist_artistgenrereferences_chords'),
    ]

    operations = [
        migrations.AddField(
            model_name='chords',
            name='artist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='chords.Artist'),
        ),
    ]
