# Generated by Django 2.0.3 on 2018-03-12 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0005_chords_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChordGenreReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Chords',
            new_name='Chord',
        ),
        migrations.AddField(
            model_name='chordgenrereferences',
            name='chord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chords.Chord'),
        ),
        migrations.AddField(
            model_name='chordgenrereferences',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chords.Genre'),
        ),
    ]
