# Generated by Django 2.0.3 on 2018-03-13 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0007_auto_20180312_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chord',
            name='artist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='chords', to='chords.Artist'),
        ),
    ]
