# Generated by Django 2.0.3 on 2018-03-18 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0008_auto_20180313_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistgenrereference',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_genres', to='chords.Artist'),
        ),
        migrations.AlterField(
            model_name='chordgenrereference',
            name='chord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chord_genres', to='chords.Chord'),
        ),
    ]
